server {
    listen 80;
    server_name forager.lindsayschwartz.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name forager.lindsayschwartz.com;

    ssl_certificate /etc/letsencrypt/live/forager.lindsayschwartz.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/forager.lindsayschwartz.com/privkey.pem;

    server_tokens off;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    client_max_body_size 10m;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Connection '';
        proxy_http_version 1.1;
    }

    location /media/ {
        proxy_pass http://backend:8000/media/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

}
