"""create users and discoveries tables

Revision ID: 238dc6f26cd0
Revises: 
Create Date: 2026-02-17 17:06:36.325996

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '238dc6f26cd0'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=False),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('default_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dietary_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=False)
    op.create_table('discoveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_notes', sa.String(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('species_prediction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('all_predictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('safety_verdict', sa.String(length=50), nullable=True),
    sa.Column('safety_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nutrition_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weather_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_reasoning_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discoveries_session_id'), 'discoveries', ['session_id'], unique=False)
    op.create_index(op.f('ix_discoveries_user_id'), 'discoveries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discoveries_user_id'), table_name='discoveries')
    op.drop_index(op.f('ix_discoveries_session_id'), table_name='discoveries')
    op.drop_table('discoveries')
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
