"""add heatmap_url to discoveries

Revision ID: 61bc1a0c105b
Revises: a7c3e9f1b204
Create Date: 2026-03-16 12:04:27.752183

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '61bc1a0c105b'
down_revision: str | Sequence[str] | None = 'a7c3e9f1b204'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discoveries', sa.Column('heatmap_url', sa.String(), nullable=True))
    op.drop_constraint(op.f('uq_users_oauth_provider_oauth_id'), 'users', type_='unique')
    op.create_index('ix_user_oauth', 'users', ['oauth_provider', 'oauth_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_oauth', table_name='users')
    op.create_unique_constraint(op.f('uq_users_oauth_provider_oauth_id'), 'users', ['oauth_provider', 'oauth_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('discoveries', 'heatmap_url')
    # ### end Alembic commands ###
