"""add plant_knowledge table

Revision ID: e346042376c0
Revises: 61bc1a0c105b
Create Date: 2026-03-20 10:33:50.338601

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e346042376c0'
down_revision: str | Sequence[str] | None = '61bc1a0c105b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('species_class_name', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_knowledge_species_class_name'), 'plant_knowledge', ['species_class_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plant_knowledge_species_class_name'), table_name='plant_knowledge')
    op.drop_table('plant_knowledge')
    # ### end Alembic commands ###
